name: Release please workflow

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-pr:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: googleapis/release-please-action@v3
        id: release-please
        with:
          path: .
          changelog-path: CHANGELOG.md
          command: release-pr
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module