name: Release please workflow

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  tf:
    uses: dsb-norge/github-actions-terraform/.github/workflows/terraform-module-release@relesase
    secrets: inherit
    permissions:
        contents: write  # required for checkout action. 
        id-token: write # required for Azre passwodless login
        pull-requests: write # required for commenting on PR
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}